name: Sylva E2E Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build-e2e-images:
    name: Build & Run E2E Images
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          # We run into rate limiting issues if we don't authenticate
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install requirements
        run: |
          sudo apt update
          sudo snap install go --classic --channel=1.23/stable
      - name: Build provider images
        run: make docker-build-e2e
      - name: Save images to a public registry
        run: |
          # TBD
          docker image ls
      - name: Build configs
        run: make release
      - name: Save configs to a public release url
        run: |
          # TBD
          ls out/*.yaml
  
  run-e2e-tests:
    name: Run Sylva E2E Tests
    runs-on: ubuntu-latest
    needs: build-e2e-images
    strategy:
      fail-fast: true
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          # We run into rate limiting issues if we don't authenticate
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install requirements
        run: |
          sudo apt update
          sudo apt install yamllint --yes
      - name: Increase inotify watches
        run: |
          # Prevents https://cluster-api.sigs.k8s.io/user/troubleshooting#cluster-api-with-docker----too-many-open-files
          sudo sysctl fs.inotify.max_user_watches=1048576
          sudo sysctl fs.inotify.max_user_instances=8192
      - name: Clone Sylva
        run: |
          git clone https://gitlab.com/sylva-projects/sylva-core
      - name: Run Sylva
        run: |
          cd sylva-core
          BOOTSTRAP_WATCH_TIMEOUT_MIN=1 ./bootstrap.sh environment-values/ck8s-capm3-virt

